---
- become: yes
  hosts: corda
  vars_files:
    - ./defaults/main.yml
  tasks:
    - name: Add Zulu.org JDK key
      rpm_key:
          key: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
          state: present

    - name: Add Zulu.org JDK repository
      yum_repository:
          name: zulu
          description: Zulu.org OpenJDK repo
          baseurl: "http://repos.azulsystems.com/rhel/$releasever/$basearch"
          gpgcheck: yes
          state: present

    - name: Install OpenJDK (Zulu build)
      yum:
        pkg: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - zulu-8

    - name: Create group
      group:
        name: "{{ corda_user }}"
        state: present

    - name: Create user
      user:
        name: "{{ corda_user }}"
        groups: "{{ corda_user }}"
        state: present
        createhome: no
        shell: /bin/false

    - name: Prepare Corda directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ corda_user }}"
        group: "{{ corda_user }}"
        mode: 0755
      loop:
        - "{{ corda_dir_location }}"
        - "{{ corda_dir_location }}/certificates"

    - name: Install systemd startup file
      template:
        src: "./templates/{{ item }}.service.j2"
        dest: /etc/systemd/system/{{ item }}.service
        owner: root
        group: root
        mode: 0755
      loop:
        - corda_node
      notify:
        - restart corda_node

    - name: Install config file
      template:
        src: ./templates/node.conf.j2
        dest: "{{ corda_dir_location }}/node.conf"
        owner: "{{ corda_user }}"
        group: "{{ corda_user }}"
        mode: 0755
      when: corda_version is version('3','>=')

    # For jars from local directory
    - name: Get corda jars from local file
      copy:
        src: "./files/{{ item }}"
        dest: "{{ corda_dir_location }}"
        owner: "{{ corda_user }}"
        group: "{{ corda_user }}"
        mode: 0755
      loop:
        - corda.jar
      notify:
        - start corda_node

    - name: Copy network-truststore
      copy:
        src: "{{ corda_local_path }}/network-root-truststore.jks"
        dest: "{{ corda_dir_location }}/certificates/"
        owner: "{{ corda_user }}"
        group: "{{ corda_user }}"
        mode: 0600
      when: not corda_devmode|bool and corda_initial_registration

    - name: Register node
      shell: "java -jar corda.jar --initial-registration --network-root-truststore-password {{ corda_password_truststore }}"
      args:
        chdir: "{{ corda_dir_location }}"
      become: true
      become_user: "{{ corda_user }}"
      notify:
        - start corda_node
      when: not corda_devmode|bool and corda_initial_registration
